<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield('title')</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 12pt;
            line-height: 1.5;
            margin: 0; 
            padding: 0 10px;
        }
        
        /* KOP SURAT IMAGE FULL */
        .header-image-container {
            width: 100%;
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 3px solid #000; /* Garis bawah tetap diperlukan? Biasanya kop image sudah ada garisnya. */
            padding-bottom: 5px;
        }
        
        .header-img {
            width: 100%;
            height: auto;
            max-height: 200px; /* Batasi tinggi agar tidak terlalu makan tempat */
            object-fit: contain; /**/
        }

        /* 
           Jika gambar kop.png SUDAH ada garis bawahnya, 
           hapus border-bottom di .header-image-container dan .header-border-2 di bawah.
           Saya asumsikan gambar kop biasanya belum ada garis hitam double yang generated by code,
           atau jika sudah ada, CSS border ini bisa didisable.
           
           Sesuai request "full kop surat", biasanya sudah include garis.
           Jadi saya HILANGKAN border CSS tambahan agar tidak double.
        */

        .header-image-container {
            width: 100%;
            text-align: center;
            margin-bottom: 10px;
            border: none; /* Hapus border manual */
        }

        .header-border-2 {
            display: none; /* Hapus garis kedua manual */
        }

        /* CONTENT */
        .content { margin-top: 10px; }
        .title {
            text-align: center;
            font-size: 14pt;
            font-weight: bold;
            margin-bottom: 15px;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="header-image-container">
        @php
            $path = public_path('images/kop.png');
            $type = pathinfo($path, PATHINFO_EXTENSION);
            if (file_exists($path)) {
                $data = file_get_contents($path);
                $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
                echo '<img src="' . $base64 . '" class="header-img" alt="Kop Surat">';
            } else {
                echo '<div style="color:red; border:1px dashed red; padding:10px;">File kop.png tidak ditemukan di public/images/</div>';
            }
        @endphp
    </div>

    <!-- Garis pemisah manual dihapus karena asumsi sudah ada di gambar -->
    <!-- <div class="header-border-2"></div> -->

    <div class="content">
        @yield('content')
    </div>
</body>
</html>
